version: '3.8'

services:
  # MongoDB database service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Backend API and Socket.IO service
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017/breakfree-leaderboard
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "8000:8000"
    networks:
      - app-network

  # Frontend Next.js service
  frontend:
    build:
      context: .
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network

# Volumes for data persistence
volumes:
  mongodb_data:
    driver: local

# Networks for container communication
networks:
  app-network:
    driver: bridge