version: '3.8'

services:
  # MongoDB database service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend API and Socket.IO service
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

  # Frontend Next.js service
  frontend:
    build:
      context: .
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3006:3000"
    networks:
      - app-network

# Volumes for data persistence
volumes:
  mongodb_data:
    driver: local

# Networks for container communication
networks:
  app-network:
    driver: bridge